# Generated by Django 4.1.7 on 2023-03-16 16:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pictures',
            old_name='user',
            new_name='user_name',
        ),
    ]
