# Generated by Django 4.1.7 on 2023-05-03 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0003_rename_opinion_feedback_feedback_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pictures',
            name='pic',
            field=models.ImageField(upload_to=''),
        ),
    ]
